#!/usr/bin/python
import xml.etree.ElementTree as ET
from twisted.internet import task, protocol, reactor
from aae import console, filterlist 
from pyaae import Hashtree, Msgpuller


CONF_FILE = 'nodemon.xml'

def start_observer(xmlfile):
   pyaae.hashtree_init()
   pyaae.ht_init()
   pyaae.msgpuller_start(xmlfile)
   i = get_console_info(xmlfile)
   pyaae.console_start(*i)
   pyaae.hashtree_destroy()

def get_console_info(xmlfile):
   info = []
   tree = ET.parse(xmlfile);
   root = tree.getroot();
   info.append(root.find('./console/ip').text)
   info.append(int(root.find('./console/port').text))
   return info 

def get_metadb_info(xmlfile):
   info = {}
   tree = ET.parse(xmlfile)
   root = tree.getroot();
   info['host'] = root.find('./metadata-db/ip').text
   info['port'] = int(root.find('./metadata-db/port').text)
   info['user'] = root.find('./metadata-db/user').text
   info['db'] = root.find('./metadata-db/db').text
   info['passwd'] = root.find('./metadata-db/pass').text
   return info


def update_filter_list():
   fl.update()
   

if __name__ == '__main__':
   ht = Hashtree("db") 
   info = get_metadb_info(CONF_FILE)
   fl = filterlist.FilterList(info)
   mp = Msgpuller(CONF_FILE, ht, fl._filterlist)
   #start msg puller
   mp.start()
   #update filter list periodically.
   l = task.LoopingCall(update_filter_list)
   l.start(10)
   #start console
   console.set_hashtree(ht)
   ip, port = get_console_info(CONF_FILE)
   reactor.listenTCP(port, console.AaeConsoleFactory(), interface=ip) 
   reactor.run()
   
